### ISSUE TITLE
Patcher doesn't take winning overrides

### ISSUE THREAD

**Issue by saberthesword** [ReaperAnon/True-Unleveled-Skyrim#2]
Tried running the patcher and for some reason it's not copying the records last in the load order.

![image](https://user-images.githubusercontent.com/61779318/144737214-76f6bc30-41d1-4d57-8d07-8d133d4ea061.png)
![image](https://user-images.githubusercontent.com/61779318/144737243-dd9e1b03-9703-4b8f-a664-3797d480f73d.png)

Am I doing something wrong here?

**Comment by ReaperAnon** [comment]
I believe that was an issue with Mutagen that has been fixed since, gonna close this.
