### ISSUE TITLE
Request: Apply Encounter Zones on selected plugins

### ISSUE THREAD

**Issue by voiceinthedark** [ReaperAnon/True-Unleveled-Skyrim#3]
It would be great if Encounter Zones patching could be applied only on certain selected plugins, or simply skipping all vanilla EZs since those can be patched with MLU-EZ or Arena; while new lands like Bruma or Vigilant lack any EZ tweaking.
Right now I am resorting to applying the patch then manually removing all records pertaining to vanilla EZs

**Comment by ReaperAnon** [comment]
Well, I haven't touched it in a while, but if you still care I did add it for the small rework. Good idea.
