### ISSUE TITLE
Cannot compile latest version in Synthesis

### ISSUE THREAD

**Issue by tex111** [ReaperAnon/True-Unleveled-Skyrim#4]
Patch\NPCs.cs(348,103): error CS0246: The type or namespace name 'FunctionConditionData' could not be found (are you missing a using directive or an assembly reference?)
Patch\NPCs.cs(355,108): error CS0165: Use of unassigned local variable 'requiredPerk'
Patch\NPCs.cs(348,103): error CS0246: The type or namespace name 'FunctionConditionData' could not be found (are you missing a using directive or an assembly reference?)
Patch\NPCs.cs(355,108): error CS0165: Use of unassigned local variable 'requiredPerk'

Did you add some sort of dependancy?

**Comment by AninoGamingTV** [comment]
Having the issue as well

**Comment by Laserdrucker95** [comment]
Same problem here.

**Comment by ReaperAnon** [comment]
Updated it now.
