### ISSUE TITLE
No Nexus page - Is this still supported?

### ISSUE THREAD

**Issue by LoganSchmalz** [ReaperAnon/True-Unleveled-Skyrim#6]
I happened to notice the Nexus page for this was deleted, is it still supported?

**Comment by ReaperAnon** [comment]
Not sure what you mean by supported exactly, it works. The nexus page was always just a front for this.

**Comment by LoganSchmalz** [comment]
I was just curious if for some reason you had intended to take this GitHub repository down as well, I was hoping that wasn't the case. It had been a while since I looked at the Nexus page so I forgot what was on there. Sorry if I wasted some of your time by opening an issue. Thanks!

**Comment by ReaperAnon** [comment]
No, not at all, don't worry. lol
The nexus is just full of and ran by disgusting weird people, I didn't want anything of mine on there.
